services:
  cs3528_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      default:
        aliases:
          - myprofile
    command: ["--config", "gunicorn_config.py", "app:app"]

networks:
  default:
    name: nginx_proxy
    external: true
