services:
  cs3528_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      default:
        aliases:
          - myprofile
    command: ["gunicorn", "--config", "gunicorn_config.py", "app:app"]

networks:
  default:
    name: nginx_proxy
    external: true
