name: CI and Coverage

on:
    pull_request:
        branches: ["main", "master"]

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.11.0
              with:
                  mongodb-version: "8.0"
                  mongodb-replica-set: test-rs
              env:
                  CI: true
                  IS_GITHUB_ACTION: "True"
                  IS_TEST: "True"
                  MONGO_DB_TEST: "cs3528_test"
                  SUPERUSER_EMAIL: "dummy@admin.com"
                  SUPERUSER_PASSWORD: "dummy"

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest coverage
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run tests with coverage
              env:
                  SECRET_KEY: "psZsPEYjcq9@?(!6w=dK" # Fake secret key
                  IS_TEST: "True"
                  MONGO_DB_TEST: "cs3528_test"
                  IS_GITHUB_ACTION: "True"
                  SUPERUSER_EMAIL: "dummy@admin.com"
                  SUPERUSER_PASSWORD: "dummy"
              run: |
                  coverage run -m pytest
                  coverage xml -o coverage.xml

            - name: Lint with pylint
              run: |
                  pylint --disable=W1203 .

            - name: Upload Coverage Report
              uses: orgoro/coverage@v3.2
              with:
                  coverageFile: coverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
